channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - bz2file=0.98=py_0
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - cloudpickle=0.8.1=py_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask-core=1.2.1=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=nompi_py36hf008753_1102
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=h211956c_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.3=199
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.7.1=h8b12597_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=2.6.11=py_0
  - matplotlib=3.0.3=py36h5429711_0
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - nibabel=2.4.0=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1c=h7b6447c_1
  - pcre=8.43=he6710b0_0
  - pillow=6.0.0=py36h34e0f95_0
  - pip=19.1=py36_0
  - protobuf=3.7.1=py36he1b5a44_0
  - pycparser=2.19=py36_0
  - pydicom=1.2.2=py_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py36hdd07704_1
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py36he6710b0_0
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.13=py36he6710b0_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tensorboard=1.13.1=py36_0
  - tensorboardx=1.6=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - torchvision=0.4.0=py36_cu100
  - tornado=6.0.2=py36h7b6447c_0
  - tqdm=4.31.1=py_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0

